package com.sebastmar.module.report.configuration

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class ReportStringsTest {

    private val reportStrings = ReportStrings()

    @Test
    fun `verify the default top section`() {
        val givenDefaultTop = "# Updated Modules"

        val result = reportStrings

        assertEquals(givenDefaultTop, result.topSection)
    }

    @Test
    fun `verify the default bottom section`() {
        val givenDefaultBottom = "_Generated by [danger-modules-report](https://github.com/SebVay/Danger-Module-Report)_ with ❤️"

        val result = reportStrings

        assertEquals(givenDefaultBottom, result.bottomSection)
    }

    @Test
    fun `verify the incorrect host warning`() {
        val givenDefaultWarning = """
            🚧🚧🚧
            ### `githubModuleReport` has been called outside a Github context.
            Use it only for local testing, some functionalities or html link could be missing.
            🚧🚧🚧
        """.trimIndent()

        val result = reportStrings

        assertEquals(givenDefaultWarning, result.incorrectHostWarning)
    }
}
