package com.sebastmar.module.report.configuration

public data class ReportStrings(

    /**
     * A text to be displayed at the top of the report, markdown compatible.
     *
     * By default: `# Updated Modules`
     *
     * If set to `null`, no top section will be displayed.
     */
    val topSection: String? = "# Updated Modules",

    /**
     * A text to be displayed at the bottom of the report, markdown compatible.
     *
     * By default: `null` (no bottom section will be displayed)
     *
     * If set to a String, this text will be displayed at the bottom of the report.
     */
    val bottomSection: String? =
        "_Generated by [danger-modules-report](https://github.com/SebVay/Danger-Module-Report)_ with ❤️",

    val incorrectHostWarning: String? = """
            🚧🚧🚧
            ### `githubModuleReport` has been called outside a Github context.
            Use it only for local testing, some functionalities or html link could be missing.
            🚧🚧🚧
    """.trimIndent(),
)
